export const products = [
  {
    id: 1,
    title: "Fresh organic vila farm lomon 500gm pack",
    brand: "NestFood",
    category: "Snack",
    tag: "Hot",
    rating: 4.0,
    price: 28.85,
    oldPrice: 32.8,
    image: "/products/product-1.svg",
    
  },
  {
    id: 2,
    title: "Best snakes with hazel nut pack 200gm",
    brand: "Stouffer",
    category: "Hodo Foods",
    tag: "Sale",
    rating: 3.5,
    price: 52.85,
    oldPrice: 55.8,
    image: "/products/product-2.svg",
  },
  {
    id: 3,
    title: "Organic fresh venila farm watermelon 5kg",
    brand: "StarKist",
    category: "Snack",
    tag: "New",
    rating: 4.0,
    price: 48.85,
    oldPrice: 52.8,
    image: "/products/product-3.svg",
  },
  {
    id: 4,
    title: "Fresh organic apple 1kg simla marmimg",
    brand: "NestFood",
    category: "Vegetables",
    rating: 4.0,
    price: 17.85,
    oldPrice: 19.8,
    image: "/products/product-4.svg",
  },
  {
    id: 5,
    title: "Blue Diamond Almonds Lightly Salted Vegetables",
    brand: "NestFood",
    category: "Pet Foods",
    tag: "-14%",
    rating: 4.0,
    price: 23.85,
    oldPrice: 25.8,
    image: "/products/product-5.svg",
  },
  {
    id: 6,
    title: "Chobani Complete Vanilla Greek Yogurt",
    brand: "NestFood",
    category: "Hodo Foods",
    rating: 4.0,
    price: 54.85,
    oldPrice: 55.8,
    image: "/products/product-6.svg",
  },
  {
    id: 7,
    title: "Canada Dry Ginger Ale - 2 L Bottle - 200ml - 400g",
    brand: "NestFood",
    category: "Meats",
    rating: 4.0,
    price: 32.85,
    oldPrice: 33.8,
    image: "/products/product-7.svg",
  },
  {
    id: 8,
    title: "Encore Seafoods Stuffed Alaskan Salmon",
    brand: "NestFood",
    category: "Snack",
    tag: "Sale",
    rating: 4.0,
    price: 35.85,
    oldPrice: 37.8,
    image: "/products/product-8.svg",
  },
  {
    id: 9,
    title: "Gorton’s Beer Battered Fish Fillets with soft paper",
    brand: "Old El Paso",
    category: "Coffes",
    tag: "Hot",
    rating: 4.0,
    price: 23.85,
    oldPrice: 25.8,
    image: "/products/product-9.svg",
  },
  {
    id: 10,
    title: "Haagen-Dazs Caramel Cone Ice Cream Ketchup",
    brand: "Tyson",
    category: "Cream",
    rating: 2.0,
    price: 22.85,
    oldPrice: 24.8,
    image: "/products/product-10.svg",
  },
];
export const bestSells = [
  {
    id: 11,
    title: "All Natural Italian-Style Chicken Meatballs",
    brand: "Hodo Foods",
    category: "Meats",
    tag: "Save 33%",
    rating: 4.0,
    price: 238.85,
    oldPrice: 245.8,
    sold: "90/120",
    image: "/products/sells/sells-1.svg",
  },
  {
    id: 12,
    title: "Angie’s Boomchickapop Sweet and Womnies",
    brand: "Hodo Foods",
    category: "Snack",
    tag: "Sale",
    rating: 4.0,
    price: 238.85,
    oldPrice: 245.8,
    sold: "90/120",
    image: "/products/sells/sells-2.svg",
  },
  {
    id: 13,
    title: "Foster Farms Takeout Crispy Classic",
    brand: "Hodo Foods",
    category: "Snack",
    tag: "Best sale",
    rating: 4.0,
    price: 238.85,
    oldPrice: 245.8,
    sold: "90/120",
    image: "/products/sells/sells-3.svg",
  },
  {
    id: 14,
    title: "Blue Diamond Almonds Lightly Salted",
    brand: "Hodo Foods",
    category: "Snack",
    tag: "Save 15%",
    rating: 4.0,
    price: 238.85,
    oldPrice: 245.8,
    sold: "90/120",
    image: "/products/sells/sells-4.svg",
  },
  // منتجات إضافية
  {
    id: 15,
    title: "Organic Avocado Hass 1kg",
    brand: "FreshFarm",
    category: "Vegetables",
    tag: "New",
    rating: 5.0,
    price: 45.5,
    oldPrice: 52.0,
    sold: "30/100",
    image: "/products/sells/sells-2.svg",
  },
  {
    id: 16,
    title: "Ocean Spray Cranberry Juice 1L",
    brand: "Ocean Spray",
    category: "Beverages",
    tag: "Hot",
    rating: 4.5,
    price: 18.75,
    oldPrice: 22.0,
    sold: "60/200",
    image: "/products/sells/sells-4.svg",
  },
  {
    id: 17,
    title: "Barilla Italian Spaghetti Pasta 500g",
    brand: "Barilla",
    category: "Pasta",
    tag: "Save 10%",
    rating: 4.3,
    price: 12.5,
    oldPrice: 14.0,
    sold: "150/300",
    image: "/products/sells/sells-2.svg",
  },
  {
    id: 18,
    title: "Kirkland Organic Almond Butter 680g",
    brand: "Kirkland",
    category: "Nut Butters",
    tag: "Sale",
    rating: 4.8,
    price: 165.0,
    oldPrice: 185.0,
    sold: "75/150",
    image: "/products/sells/sells-1.svg",
  },
];
